name: Deploy Helm Chart to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Minikube
      uses: kubevirt/minikube-setup-action@v1
      with:
        minikube_version: latest
        kubernetes_version: latest

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod +x get_helm.sh
        ./get_helm.sh

    - name: Add Helm Repository
      run: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Deploy Helm Chart
      run: helm install my-keycloak bitnami/keycloak --version 19.0.0
